[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "0.10.6" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
uuid = "1.2.2"