version: '3.6'

services:

  postgresql:
    image: postgres:12.13-alpine3.17
    user: postgres
    environment:
      - POSTGRES_USER=watchkcals
      - POSTGRES_DB=watchkcals
      - POSTGRES_PASSWORD=watchkcals
    ports:
      - 5432:5432
    volumes:
      - postgresql_core-data:/var/lib/postgresql/data
    networks:
      - watch_kcals

  front:
    image: node:lts-slim
    volumes:
      - ./front:/app
    working_dir: /app
    command: bash -c "yarn install && yarn global add @quasar/cli && quasar dev -p 8080"
    ports:
      - "8080:8080"
    depends_on:
      - back
    networks:
      - watch_kcals

  back:
    build:
      context: ./back/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./back:/app
    working_dir: /app
    command: bash -c "cargo watch -x run"
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    networks:
      - watch_kcals

volumes:
  postgresql_core-data:
    driver: local

networks:
  watch_kcals: {}
